# ----------------------------------------------------
#   EAVS 2016
#   unit-level tables for Joyce states
#   using same column setup as state tables
# ----------------------------------------------------


# uses the same data as generated by the aggregate file



# ----------------------------------------------------
#   Auxiliary County-level FIPS file
# ----------------------------------------------------

# maybe this will come in handy
# if only for checking that the counties in the EAVS are correct FIPS

# county FIPS comes from
# https://www.census.gov/geo/reference/codes/cou.html
# which was then saved in a text file

list.files("data/census")

census_fips <-
  read_delim(here("data/census/census-fips-2010.txt"),
             col_names = c("State", "state_fips",
                           "county_fips", "county_name", "class_fips"),
             delim = ",") %>%
  print()





# Which Joyce units have "county-like" FIPS codes
# create an indicator and then tabulate by state
d <- d %>%
  mutate(good_ending =
           str_sub(FIPSCode, start = -5L, end = -1L) == "00000") %>%
  print()

d %$%
table(State, good_ending, exclude = NULL)

# limit to Great Lakes states
d %>%
filter(State %in% joyce_states) %$%
table(State, good_ending, exclude = NULL)




# ----------------------------------------------------
#   checking Illinois
# ----------------------------------------------------

# Objective:
# if we want jurisdiction-level tables,
# we want verify that jurisdictions aren't double-counting registrants

# CHECK:
# if the city registered is > than the county registered, no double counting
# if the total registered is > than the county population, double count

# focusing on the 'problematic' jurisdictions in IL
d %>%
filter(State == "IL") %>%
filter(good_ending == FALSE)


# use the web to find out which counties these cities are in
# and then search for county names in the Jurisdiction variable
# compare county populations to registrants to check double counting

# --- aurora city (Kane, Du Page, Kendall, Will Counties)

d %>%
filter(State == "IL") %>%
select(JurisdictionName, A1a) %>%
filter(str_detect(JurisdictionName, "AURORA") |
       str_detect(JurisdictionName, "DU PAGE") |
       str_detect(JurisdictionName, "KANE") |
       str_detect(JurisdictionName, "KENDALL") |
       str_detect(JurisdictionName, "WILL COUNTY")
       ) %>%
mutate(pops = c(197899, 916924, 530847, 123355, 687263),
       county_pop = sum(pops[-1], na.rm = TRUE),
       county_reg = sum(A1a[-1], na.rm = TRUE),
       total_reg = sum(A1a, na.rm = TRUE),
       unit_ratio = A1a / pops,
       total_reg_county_pop = total_reg / county_pop,
       dbl = total_reg > county_pop,
       no_dbl = A1a > county_reg)

# Wikipedia 2010 populations:
# aurora: 197,899

# --- Bloomington (McLean County) -----------------------
d %>%
filter(State == "IL") %>%
select(JurisdictionName, A1a, good_ending) %>%
filter(str_detect(JurisdictionName, "BLOOMINGTON") |
       str_detect(JurisdictionName, "MCLEAN")) %>%
mutate(pops = c(78005, 169572),
       county_pop = sum(pops[-1], na.rm = TRUE),
       county_reg = sum(A1a[-1], na.rm = TRUE),
       total_reg = sum(A1a, na.rm = TRUE),
       unit_ratio = A1a / pops,
       total_reg_county_pop = total_reg / county_pop,
       dbl = total_reg > county_pop,
       no_dbl = A1a > county_reg)




# --- Danville (VERMILION County) -----------------------
d %>%
filter(State == "IL") %>%
select(JurisdictionName, A1a, good_ending) %>%
filter(str_detect(JurisdictionName, "DANVILLE") |
       str_detect(JurisdictionName, "VERMILION")) %>%
mutate(pops = c(33027, 81625),
       county_pop = sum(pops[-1], na.rm = TRUE),
       county_reg = sum(A1a[-1], na.rm = TRUE),
       total_reg = sum(A1a, na.rm = TRUE),
       unit_ratio = A1a / pops,
       total_reg_county_pop = total_reg / county_pop,
       dbl = total_reg > county_pop,
       no_dbl = A1a > county_reg)



# --- east st louis (st clair County) -----------------------
d %>%
filter(State == "IL") %>%
select(JurisdictionName, A1a, good_ending) %>%
filter(str_detect(JurisdictionName, "EAST ST. LOUIS") |
       str_detect(JurisdictionName, "ST. CLAIR")) %>%
mutate(pops = c(270056, 27006),
       county_pop = sum(pops[-2], na.rm = TRUE),
       county_reg = sum(A1a[-2], na.rm = TRUE),
       total_reg = sum(A1a, na.rm = TRUE),
       unit_ratio = A1a / pops,
       total_reg_county_pop = total_reg / county_pop,
       dbl = total_reg > county_pop,
       no_dbl = A1a > county_reg)



# --- GALESBURG (Knox County) -----------------------
d %>%
filter(State == "IL") %>%
select(JurisdictionName, A1a, good_ending) %>%
filter(str_detect(JurisdictionName, "GALESBURG") |
       str_detect(JurisdictionName, "KNOX")) %>%
mutate(pops = c(52919, 32195),
       county_pop = sum(pops[-2], na.rm = TRUE),
       county_reg = sum(A1a[-2], na.rm = TRUE),
       total_reg = sum(A1a, na.rm = TRUE),
       unit_ratio = A1a / pops,
       total_reg_county_pop = total_reg / county_pop,
       dbl = total_reg > county_pop,
       no_dbl = A1a > county_reg)


# things appear not to be double-counted?
# proceed??
beepr::beep(2)



# ----------------------------------------------------
#   create municipal level tables
# ----------------------------------------------------

# Algorithm:
# for each EAVS section, for each state
# create jurisdiction-level output folder (per section per state)
# grab variable names from state tables
# use those names to select columns from EAVS
# list DF by state
# lapply save table for each state (folder for each state also)


# outer loop: section folders
for (section in list.files(here("output/EAVS/state"))) {

  # output folder per section per state
  dir.create(paste0(here("output/EAVS/jurisdiction/"), section))
  lapply(joyce_states, function(state)
    dir.create(paste0(here("output/EAVS/jurisdiction/"), section, "/", state)))

  # inner loop: files within sections
  for (file in list.files(paste0(here("output/EAVS/state/"), section))) {

    cols <- read_csv(paste0(here("output/EAVS/state/"), section, "/", file)) %>%
      select(-State, -jurisdictions, -joyce,
             -contains("other"), -ends_with("_N")) %>%
      names()

    df_list <- d %>%
      filter(State %in% joyce_states) %>%
      .[, c("State", "JurisdictionName", cols)] %>%
      split(.$State)

    lapply(names(df_list), function(x)
           write_csv(df_list[[x]],
                     paste0(here("output/EAVS/jurisdiction/"), section, "/", x, "/", x, "-munic-", file)))

  } # end file loop

} # end section loop
